### ISSUE TITLE
Feature Request: Mermaid Diagram Support

### ISSUE THREAD

**Issue by ianfhunter** [Mara-Li/owlly-house#2]
Obsidian supports mermaid graphs.

I think it may not be too difficult to add to support them in the web?

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0-rc.8/mermaid.min.js"></script>  
<script>mermaid.initialize({startOnLoad:true});</script>  
```

Already, the blog creates <code> tags with class "mermaid-code".
Mermaid.JS looks for <div> tags with class "mermaid"  - but I think it can be configured in the init function
```
mermaid.init(undefined, ".mermaid-code");
```
I don't know if init and initalize are different, but i guess the full code could look something like thi:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0-rc.8/mermaid.min.js"></script>  
<script>mermaid.initialize({startOnLoad:true},  ".mermaid-code");</script>  
```

**Related Links:**
- https://www.cloudhadoop.com/2018/08/mermaidjs-tutorial-javascript-diagram.html
- https://mermaid-js.github.io/mermaid/#/usage

**Comment by ianfhunter** [comment]
Btw, there may be a bug with mixing code sections and admonition tags - I am investigating

**Comment by Mara-Li** [comment]
Normally, mermaid are supported by jekyll spaceship

https://github.com/jeffreytse/jekyll-spaceship#4-mermaid-usage

**Comment by ianfhunter** [comment]
Oh! Thank you, I will investigate more

**Comment by Mara-Li** [comment]
After some test with the script, yes, I found the problem : 
```python
   for i in range(0, len(file_data)):
        if re.search("[`?!]{3}( ?)ad-(.*)", file_data[i]):
            start = i
            start_list.append(start)
        elif re.match("```", file_data[i]) or re.match("--- admonition", file_data[i]):
            end = i
            end_list.append(end)
```
It seems to "create couple" with the last brackets of the mermaid

**Comment by ianfhunter** [comment]
I think we may need to replace
```\`\`\`mermaid```
with 
```\`\`\`mermaid!```

**Comment by Mara-Li** [comment]
Yeap, it's also done in my side, but I block on the "couple". 
With my test, I have a "start" with one value, and end with two value. So the zip create a list with the 2 first.
Something like : 
start = [7]
end = [5, 10]
zip resultat = [7,5]

If you have an idea ?

**Comment by Mara-Li** [comment]
Okay, I think i found a way. I need to do some test before push

**Comment by ianfhunter** [comment]
Great :)

**Comment by Mara-Li** [comment]
or not :<
Pretty difficult to found a way around this, tbh

**Comment by ianfhunter** [comment]
Have you pushed your branch? Maybe I can take a look

**Comment by Mara-Li** [comment]
I pushed the dev branch !

**Comment by Mara-Li** [comment]
Okay, so I work a lot, but I think i found a solution.
It's totally cursed, but it's work
